---
fixtures:
  repositories:
    download_file: https://github.com/voxpupuli/puppet-download_file
    powershell: https://github.com/puppetlabs/puppetlabs-powershell
    stdlib: https://github.com/puppetlabs/puppetlabs-stdlib
    win_facts: https://github.com/liamjbennett/puppet-win_facts
